//
//  ListExpansionsInteractor.swift
//  DominionDeckBuilder
//
//  Created by David on 2/2/17.
//  Copyright (c) 2017 damarte. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ListExpansionsInteractorInput
{
    func fetchExpansions(request: ListExpansions.FetchExpansions.Request)
}

protocol ListExpansionsInteractorOutput
{
    func presentFetchedExpansions(response: ListExpansions.FetchExpansions.Response)
}

class ListExpansionsInteractor: ListExpansionsInteractorInput
{
    var output: ListExpansionsInteractorOutput!
    var expansionsWorker = ExpansionsWorker(expansionStore:ExpansionsAPI())
    
    // MARK: - Business logic
    
    func fetchExpansions(request: ListExpansions.FetchExpansions.Request)
    {
        expansionsWorker.fetchExpansions { (expansions) in
            let response = ListExpansions.FetchExpansions.Response(expansions: expansions)
            self.output.presentFetchedExpansions(response: response)
        }
    }
}
