//
//  ListExpansionsModels.swift
//  DominionDeckBuilder
//
//  Created by David on 2/2/17.
//  Copyright (c) 2017 damarte. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct ListExpansions
{
    struct FetchExpansions
    {
        struct Request
        {
        }
        struct Response
        {
            var expansions: [Expansion]
        }
        struct ViewModel
        {
            struct DisplayedExpansion
            {
                var name: String
                var numCards: Int
            }
            var displayedExpansions: [DisplayedExpansion]
        }
    }
}
