//
//  ListExpansionsPresenter.swift
//  DominionDeckBuilder
//
//  Created by David on 2/2/17.
//  Copyright (c) 2017 damarte. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ListExpansionsPresenterInput
{
  func presentFetchedExpansions(response: ListExpansions.FetchExpansions.Response)
}

protocol ListExpansionsPresenterOutput: class
{
  func displayFetchedExpansions(viewModel: ListExpansions.FetchExpansions.ViewModel)
}

class ListExpansionsPresenter: ListExpansionsPresenterInput
{
  weak var output: ListExpansionsPresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentFetchedExpansions(response: ListExpansions.FetchExpansions.Response)
  {
    var displayedExpansions: [ListExpansions.FetchExpansions.ViewModel.DisplayedExpansion] = []
    
    for expansion in response.expansions {
        let displayedExpansion = ListExpansions.FetchExpansions.ViewModel.DisplayedExpansion(name: expansion.name, numCards: expansion.numCards)
        displayedExpansions.append(displayedExpansion)
    }
    
    let viewModel = ListExpansions.FetchExpansions.ViewModel(displayedExpansions: displayedExpansions)
    output.displayFetchedExpansions(viewModel: viewModel)
  }
}
